# Define the mode of Edit Center
NONE_MODE = 0
REF_MODE = 1
ROI_MODE = 2
MASK_MODE = 3

# Define the mode of mouse state
MOUSE_STATE_NONE = 0
MOUSE_STATE_DRAW_POINTS = 1

LST_NEED_MOUSE_TRACKING = [REF_MODE, ROI_MODE]

# View Mode
VIEW_ORIGIN_MODE = 0
VIEW_MASK_MODE = 1
VIEW_CONTOURS_MODE = 2
VIEW_HISTOGRAM_MODE = 3
